
Tok_(par    ,Mny(One(lvalue),One(list)))
Tok_(lvalue ,One(name))
Tok_(list   ,And(Quo("("), Or(One(ors),One(ands),One(item), One(list)),Quo(")")))
Tok_(ors    ,And(One(item),Mny(Quo("|"),Or(One(ands),One(item)))))
Tok_(ands   ,And(One(item),Mny(item)))
Tok_(item   ,Or(One(named),One(quote),One(regx)))
Tok_(named  ,And(One(name),Opt(cardi)))
Tok_(quote  ,Regx("^\"([^\"]*)\""))
Tok_(regx   ,Regx("^'\'(.*)\'"))
Tok_(cardi  ,Or(One(any),One(mny),One(opt)))
Tok_(any    ,Quo("*"))
Tok_(mny    ,Quo("+"))
Tok_(opt    ,Quo("?"))
Tok_(name   ,Regx("^([A-Za-z_]([A-Za-z0-9_])+)"))
Tok_(cmt    ,Regx("^[/][/][ ]*(.*?)[\r\n]+|^[ \r\n\t]+"))
